export const cards = [
  {
    id: 306,
    title: "4Story",
    thumbnail: "https://www.freetogame.com/g/306/thumbnail.jpg",
    short_description:
      "A enjoyable MMORPG where you can customize your character, join guilds and battle other factions.",
    game_url: "https://www.freetogame.com/open/4story",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Zemi Interactive",
    developer: "Zemi Interactive",
    release_date: "2008-10-20",
    freetogame_profile_url: "https://www.freetogame.com/4story",
  },
  {
    id: 292,
    title: "5Street",
    thumbnail: "https://www.freetogame.com/g/292/thumbnail.jpg",
    short_description:
      "A free-to-play dancing MMO and a unique social experience.",
    game_url: "https://www.freetogame.com/open/5street",
    genre: "Social",
    platform: "PC (Windows)",
    publisher: "Snail Games",
    developer: "Snail Games",
    release_date: "2011-11-11",
    freetogame_profile_url: "https://www.freetogame.com/5street",
  },
  {
    id: 181,
    title: "8BitMMO",
    thumbnail: "https://www.freetogame.com/g/181/thumbnail.jpg",
    short_description:
      "A free to play retro­-style 2D MMO and a giant construction sandbox! ",
    game_url: "https://www.freetogame.com/open/8bitmmo",
    genre: "MMORPG",
    platform: "PC (Windows), Web Browser",
    publisher: "Archive Entertainment ",
    developer: "Archive Entertainment ",
    release_date: "2015-01-26",
    freetogame_profile_url: "https://www.freetogame.com/8bitmmo",
  },
  {
    id: 265,
    title: "9Dragons",
    thumbnail: "https://www.freetogame.com/g/265/thumbnail.jpg",
    short_description:
      "A martial arts themed MMORPG set in China during the Ming Dynasty.",
    game_url: "https://www.freetogame.com/open/9dragons",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Battlezone",
    developer: "JoongWon Games",
    release_date: "2007-05-09",
    freetogame_profile_url: "https://www.freetogame.com/9dragons",
  },
  {
    id: 533,
    title: "A.V.A Global",
    thumbnail: "https://www.freetogame.com/g/533/thumbnail.jpg",
    short_description:
      "A.V.A is a free-to-play online first-person shooter with multiple game modes, unique customizations, as well as PvP and PvE gameplay.",
    game_url: "https://www.freetogame.com/open/ava",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "NEOWIZ",
    developer: "NEOWIZ",
    release_date: "2022-08-24",
    freetogame_profile_url: "https://www.freetogame.com/ava",
  },
  {
    id: 386,
    title: "Aberoth",
    thumbnail: "https://www.freetogame.com/g/386/thumbnail.jpg",
    short_description:
      "A free to play 8-bit MMORPG with retro graphics and MUD-like interface.",
    game_url: "https://www.freetogame.com/open/aberoth",
    genre: " MMORPG",
    platform: "Web Browser",
    publisher: "Jarbit",
    developer: "Jarbit",
    release_date: "2015-07-17",
    freetogame_profile_url: "https://www.freetogame.com/aberoth",
  },
  {
    id: 319,
    title: "Ace Online",
    thumbnail: "https://www.freetogame.com/g/319/thumbnail.jpg",
    short_description:
      "A free to play fast action 3D sci-fi MMO where players control space fighters jets.",
    game_url: "https://www.freetogame.com/open/ace-online",
    genre: "Shooter",
    platform: "PC (Windows)",
    publisher: "Suba Games",
    developer: "MasangSoft",
    release_date: "2008-08-29",
    freetogame_profile_url: "https://www.freetogame.com/ace-online",
  },
  {
    id: 89,
    title: "AdventureQuest 3D",
    thumbnail: "https://www.freetogame.com/g/89/thumbnail.jpg",
    short_description:
      "A free to play cross-platform MMORPG from the creators of the original 2D RPG game.",
    game_url: "https://www.freetogame.com/open/adventurequest-3d",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Artix Entertainment",
    developer: "Artix Entertainment",
    release_date: "2016-10-19",
    freetogame_profile_url: "https://www.freetogame.com/adventurequest-3d",
  },
  {
    id: 426,
    title: "AdventureQuest Worlds",
    thumbnail: "https://www.freetogame.com/g/426/thumbnail.jpg",
    short_description:
      "A free-to-play 2D fantasy browser MMORPG. There are no downloads or software to install! ",
    game_url: "https://www.freetogame.com/open/adventurequest-worlds",
    genre: "MMORPG",
    platform: "Web Browser",
    publisher: "Artix Entertainment",
    developer: "Artix Entertainment",
    release_date: "2008-10-10",
    freetogame_profile_url: "https://www.freetogame.com/adventurequest-worlds",
  },
  {
    id: 527,
    title: "Aero Tales Online",
    thumbnail: "https://www.freetogame.com/g/527/thumbnail.jpg",
    short_description:
      "Aero Tales Online: The World is a free-to-play 3D anime-style MMORPG with PvP and PvE elements. The game revolves around the “mysterious story of the Key of Skylight”.",
    game_url: "https://www.freetogame.com/open/aero-tales-online",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Anisage Games",
    developer: "Anisage Games",
    release_date: "2022-08-01",
    freetogame_profile_url: "https://www.freetogame.com/aero-tales-online",
  },
  {
    id: 301,
    title: "Age of Conan: Unchained",
    thumbnail: "https://www.freetogame.com/g/301/thumbnail.jpg",
    short_description:
      "A award ­winning massively multiplayer online game that has received critical acclaim.",
    game_url: "https://www.freetogame.com/open/age-of-conan",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Funcom",
    developer: "Funcom",
    release_date: "2008-05-20",
    freetogame_profile_url: "https://www.freetogame.com/age-of-conan",
  },
  {
    id: 232,
    title: "Age of Wushu",
    thumbnail: "https://www.freetogame.com/g/232/thumbnail.jpg",
    short_description:
      "A free-to-play martial arts action MMORPG with a large open world and sandbox-like features.",
    game_url: "https://www.freetogame.com/open/age-of-wushu",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "Snail Games",
    developer: "Snail Games",
    release_date: "2012-12-20",
    freetogame_profile_url: "https://www.freetogame.com/age-of-wushu",
  },
  {
    id: 277,
    title: "Aika Online",
    thumbnail: "https://www.freetogame.com/g/277/thumbnail.jpg",
    short_description: "A free-to-play MMORPG with large scale PvP battles.",
    game_url: "https://www.freetogame.com/open/aika-online",
    genre: "MMORPG",
    platform: "PC (Windows)",
    publisher: "HanbitSoft",
    developer: "JoyImpact",
    release_date: "2010-08-27",
    freetogame_profile_url: "https://www.freetogame.com/aika-online",
  },
];
